package collector

import (
	"time"

	"github.com/openassetwatch/openassetwatch/internal/detector"
	"github.com/openassetwatch/openassetwatch/pkg/models"
	"github.com/openassetwatch/openassetwatch/pkg/schema"
)

func CollectLocalInventory(siteID string) models.Inventory {
	asset := detector.LocalAsset(siteID)
	return models.Inventory{
		SchemaVersion: schema.InventorySchemaVersion,
		CollectedAt:   time.Now().UTC(),
		Assets:        []models.Asset{asset},
		Evidence: []models.Evidence{
			{
				Source:     "oaw_agent",
				Summary:    "Inventory generated by the passive local inventory foundation",
				Confidence: "high",
			},
		},
	}
}
